name: Consistent End-User Meta

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  meta-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install --production node-html-parser marked @octokit/rest

      - name: Download Hero program
        run: |
          curl -o update-meta.js https://raw.githubusercontent.com/darsan-in/.github/main/utils/update-meta.js

      - name: Update meta
        env:
          GITHUB_TOKEN: ${{ secrets.META_UPDATE_KEY }}
          REPO_META: ${{ github.repository }}
        run: |
          node update-meta.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add package.json
          git commit -m 'End-User Meta updated'
          git push
