name: Count Lines of Code

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Count Lines of Code (cloc)
        uses: djdefi/cloc-action@6
        with:
          options: --json --report-file=loc-meta.json

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add loc-meta.json
          git commit -m 'LOC updated'
          git push
